#!/usr/bin/env bash
# ssh config file

Host *
      PasswordAuthentication no
      IdentityFile ~/.ssh/school
      SendEnv LANG LC_*
      HashKnownHosts yes
      GSSAPIAuthentication yes
      GSSAPIDelegateCredentials no      
